### ISSUE TITLE
Elements layout question

### ISSUE THREAD

**Issue by Artgit** [alump/GridStack#10]
In my application I want to use GridStack layout in order to implement visual sorting effect.

Right now I can't vertically align elements(panels) inside my GridStack .

With a following code:

```

        GridStackLayout decisionPanel = new GridStackLayout(1);
        decisionPanel.setSizeFull();
        decisionPanel.setAnimate(true);
        decisionPanel.setCellHeight(100);

        for (int i = 0; i < 10; i++) {          
            decisionPanel.addComponent(tooltips("" + i));
        }


        sp.setSecondComponent(decisionPanel);
```

I have a following visualization:

![gridstack](https://cloud.githubusercontent.com/assets/2064812/15424337/b69b3cb8-1e8a-11e6-83a6-a9de3509d411.png)

but I need to show my panels inside GridStack as displayed at the following image(implemented with a VerticalLayout only for demo purpose):

![verticallayout](https://cloud.githubusercontent.com/assets/2064812/15424361/dc23029a-1e8a-11e6-8730-168ec470d286.png)

What am I doing wrong and how to fix it ? Thanks

**Comment by Artgit** [comment]
Even with a following code it doesn't work as expected:

```
GridStackLayout decisionPanel = new GridStackLayout(1);
decisionPanel.setSizeFull();
decisionPanel.setAnimate(true);

for (int i = 0; i < 10; i++) {  
    Button tooltips = new Button("" + i);
    decisionPanel.addComponent(tooltips, 0, i);         
}
```

For testing purpose I'm going to show 10 buttons but as you can see from a screenshot below, I have only 5.
Also, How to control vertical gaps between elements ?

![buttons](https://cloud.githubusercontent.com/assets/2064812/15429626/7f6af038-1eaa-11e6-826e-277e58a8e7ac.png)

**Comment by alump** [comment]
Try use the setCellHeight method with correct cell height.  Grid stack needs to know the height of 1 slot. As it's grid after all. You can then define height component in slots when you add those to gridstack layout.

**Comment by alump** [comment]
I assume also this ticket can be closed.
