### ISSUE TITLE
top and bottom paddings for GridStack demo

### ISSUE THREAD

**Issue by Artgit** [alump/GridStack#11]
Could you please add in your awesome example http://app.siika.fi/GridStackDemo/#!split - top and bottom paddings the same like we have from the left and right ?

**Comment by alump** [comment]
What padding you mean?

But you should be able to define those in your theme.

**Comment by Artgit** [comment]
I mean padding at the top and bottom of GridStack, the same as at left and right. Unfortunately I didn't find a way how to do it.

I have attached screenshot for more details: 
![padding](https://cloud.githubusercontent.com/assets/2064812/15464691/63ac019e-20d9-11e6-9c53-19acb175358a.png)

**Comment by alump** [comment]
One simple way to resolve this would be to add css rule:

``` css
.v-splitpanel-second-container {
  padding-top: 6px;
}
```

You might want to give own stylename to your SplitPanel to avoid this rule applying to all second containers of all SplitPanels.

**Comment by alump** [comment]
https://github.com/alump/GridStack/commit/32b21632022df7cde14ac3e777209a3ba7c32279

Example

**Comment by Artgit** [comment]
Thanks for your answer. This solution applied to SplitPanel's container.. but I have here some other components together with GridStack. I have a panel above  GridStack so with this solution I have a padding above this panel but not in GridStack component.

**Comment by alump** [comment]
if you have those components together with eg. verticallayout, just use the setSpacing(true) of it. Or just add padding to slot that contains the gridstack.

**Comment by Artgit** [comment]
Is it possible to add padding to GridStack container itself ?

**Comment by alump** [comment]
Looks like gridstack library itself doesn't provide any margin support. So it has to be done with CSS. Adding it to wrapping element is valid way to handle this. I don't think i will add wrapper to my implementation for this requirement. If nothing else you can add CssLayout as wrapper, and set padding there.
