### ISSUE TITLE
Resize component in GridStack without moving component down

### ISSUE THREAD

**Issue by Artgit** [alump/GridStack#15]
I need to programmatically resize a certain component in GridStack (new GridStackLayout(1).setCellHeight(140).setAnimate(true);).

I'm using a following method for this purpose:

`gridStack.resizeComponent(component, null, 2);`

right after that the resized component is moving to the bottom of GridStack container. How to prevent the component from moving down and leave it at its position ?

**Comment by Artgit** [comment]
And also how to get current component width and height in terms of GridStack ?

I need this values(with some modification) in order to provide in gridStack.resizeComponent(component, ?, ?);

**Comment by alump** [comment]
Are you sure it doesn't overlap with existing component in layout? gridstack on client side will find the closest free position. So might be good idea to iterate all components in layout and move those to new locations.

**Comment by Artgit** [comment]
thanks for your answer. Just for clarification, for example I have a following omponents:

1
2
3
4
5
6
7

I have to resize component 2 in order to be 2 times bigger(components 3 and the rest should be moved down), something like this

1
2
2
3
4
5
6
7

What should I do in order to achieve it ? This is one column layout

**Comment by alump** [comment]
call gridStackComponent.moveComponent(thirdComponent, 0, 3) ... moveComponent(fourthComponent, 0, 4) ... etc... just to make sure those make empty space to slot 0,2

**Comment by Artgit** [comment]
Awesome.  Thank you very much !

Could you please also help me with a following question https://github.com/alump/GridStack/issues/16 ?
