### ISSUE TITLE
Unintended move on button click 

### ISSUE THREAD

**Issue by mku1059** [alump/GridStack#2]
Clicking on a button within a widget, the listener gets called, but also dragging of the widget is activated. The click listener seems to filter the mouse up event, so the widget sticks at the mouse pointer. This effect can be reproduced with the demo app.

**Comment by alump** [comment]
This is Firefox specific issue.

**Comment by alump** [comment]
Actually now repeatable on Chrome too... looks like gridstack.js and vaadin's buttons do not like each others. This might be tricky to resolve.

**Comment by alump** [comment]
0.2.0 has a workaround, it now uses drag handles. This because gridstack.js and Vaadin components do not behave well together, if they fight over same events.

**Comment by alump** [comment]
0.2.1 will get GridStackButton that resolves issue without separate drag handle. New issues to be made with other misbehaving components.

**Comment by alump** [comment]
Both workarounds in 0.2.1
