### ISSUE TITLE
Removing and subsequently adding Components

### ISSUE THREAD

**Issue by mku1059** [alump/GridStack#3]
Removing a component (not iterating through stack but giving component explicitly) from gridstack works as expected, but afterwards a new component can't be added. Testing with the "-" and "+" buttons in the demo app shows the following results: the first remove/add component works ok, clicking "-" again still is ok, but adding components doesn't work anymore.

**Comment by alump** [comment]
My native javascript -> GWT mapping of "change" event has some issues. It's flooding error logs on other events, but in this case causes exception that breaks it.

Will fix this soon.

**Comment by alump** [comment]
0.2.0 released.
