### ISSUE TITLE
Demo Failed

### ISSUE THREAD

**Issue by klaath** [alump/GridStack#4]
Hi, I cloned the project and run the demo as it is. However, the locations, the sizes are all wrong and no drag and resize icons appear when the mouse gets on the components. ![gridstachpr](https://cloud.githubusercontent.com/assets/6582875/11588642/cd3e34c2-9a8a-11e5-95a2-fc37e5dae766.png) Looks like a CSS related problem but like I said I run as it is. Do you have any idea about what I am missing? 

One more thing, "gridStack.getOptions()" parts are showing "deprecated" in the demo. Are they replaced with a new API or will be?

Cheers,
-K

**Comment by alump** [comment]
I assume you run these steps:
- git clone
- on top folder: mvn clean install
- then on gridstack-demo folder: mvn jetty:run

These 3 magic steps should take care of all required steps. And make sure all parts are compiled (including widgetset and theme).

getOptions is temporary API. It will be replaced as soon as I add missing parts to API. Feel free to use it until then.

**Comment by alump** [comment]
I assume issue is that vaadin:update-theme step isn't run at all on demo project. This would cause missing addons.scss file on gridstack-demo/src/webapp/VAADIN/themes/demo/ folder.

If addons.scss file isn't there, then compiled css will not include any of add-on's styling rules.

Running 'mvn vaadin:theme-update' or 'mvn vaadin:theme-compile' both will update theme and generate addons.scss.

If you do have addons.scss, then something else is broken.

**Comment by klaath** [comment]
Yeap, that was the problem. I added "<goal>update-theme</goal>" to the pom file, and all works fine now. 

Many thanks,
-K

**Comment by alump** [comment]
Ok, I will also add that goal to demo project's pom.xml, to be sure.

**Comment by alump** [comment]
Closing, fixed in master.
