### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by AydinChavez** [alump/GridStack#6]
Hi,

first of all, thanks for this gread addon!

Maybe I'm missing something, but when integrating the demo app (1:1 copy of the original demo code) into my existing webapplication (View class), there are some issues:
- The overlay-icons for component resize and move are not shown at all
- There is just one column (?) visible on screen

Of course I integrated the css from the demo app.

Can you hint me to the right direction? 

Cheers, Aydin

PS: Ivy download (with information from vaadin addons page) did also not work, had to download and put jar to build-path manually.

**Comment by klaath** [comment]
Could you confirm that your web folder contains auto generated file "addons.scss" with the following content?

```
/* This file is automatically managed and will be overwritten from time to time. */
/* Do not manually edit this file. */

/* Provided by gridstack-addon-0.2.1.jar */
@import "../../../VAADIN/addons/gridstack/gridstack.scss";

/* Import and include this mixin into your project theme to include the addon themes */
@mixin addons {
    @include gridstack;
}
```

-k

**Comment by AydinChavez** [comment]
Thx for quick reaction&help.
No, this addons.scss file is completely missing. Where is its creation triggered?

**Comment by AydinChavez** [comment]
Ok, adding your proposed file solved the issue. Am still curious why I did not have this file? Is it due to not making use of the maven build process or in which process are these scss-lines added? Thanks a lot for the solution, by the way :)

**Comment by klaath** [comment]
Yeah, that file is supposed to be created by Vaadin's build plugins which is involved in the maven build process.
