### ISSUE TITLE
resources loaded twice

### ISSUE THREAD

**Issue by bsutton** [alump/GridStack#8]
using the chrome debug tools and tracing network activity I'm seeing the gridstack .js files being loaded twice:

The source code is:
` 

package com.example.gridstack;

import javax.servlet.annotation.WebServlet;

import org.vaadin.alump.gridstack.GridStackLayout;

import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
@Theme("gridstack")
public class GridstackUI extends UI {

```
@WebServlet(value = "/*", asyncSupported = true)
@VaadinServletConfiguration(productionMode = false, ui = GridstackUI.class, widgetset = "com.example.gridstack.widgetset.GridstackWidgetset")
public static class Servlet extends VaadinServlet {
}

@Override
protected void init(VaadinRequest request) {
    final VerticalLayout layout = new VerticalLayout();
    layout.setMargin(true);
    setContent(layout);


    // Creates new GridStack with 3 columns
    GridStackLayout gridStack = new GridStackLayout(3);

    // Adds label to top left corner, reserving 1 slot
    gridStack.addComponent(new Label("Hello World"), 0, 0);

    // Adds second label next to earlier, now reserving 2 slots in horizontal
    gridStack.addComponent(new Label("Lorem ipsum"), 1, 0, 2, 1);

    // Finally add label, and let client side to find location for it (will go to next row, as first is full)
    gridStack.addComponent(new Label("Find me space!"));


    layout.addComponent(gridStack);
}
```

}

`
`The network activity is:

dstack.GridstackUI$Servlet
vaadinBootstrap.js?v=7.6.5
styles.css?v=7.6.5
com.example.gridstack.widgetset.GridstackWidgetset.nocache.js?1461927154428
com.example.gridstack.GridstackUI$Servlet?v-1461927154428
09AA8E09526721723A02877391845ADF.cache.js
spinner.gif
jquery-1.11.3.min.js
OpenSans-Light-webfont.woff
jquery-ui.min.js
lodash.min.js
gridstack.js
jquery-ui.min.js
lodash.min.js
gridstack.js

`

**Comment by alump** [comment]
Yes. looks like this also happens with my demo application. I have to investigate this.

(Not sure why I do not get notifications about issues in this project, so sorry for slow response time)

**Comment by alump** [comment]
Looks like this is feature of Vaadin Framework, I will have a talk with our R&D team about this. You can see similar behaviour at http://demo.vaadin.com 's JavaScript parts.

Strange.

**Comment by alump** [comment]
Ok, got response fast. 

This is Vaadin's preload feature that makes it "load" the resources twice. With normal setup anyhow these resources are marked cacheable. and second load should come from cache.

So closing as "works as it should" and same time "can not fix" :)
